[WinEventLog://Application]
disabled = 0
index = soc_lab

[WinEventLog://Security]
disabled = 0
index = soc_lab

[WinEventLog://System]
disabled = 0
index = soc_lab

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = soc_lab
renderXml = true
